// <auto-generated />
using System;
using CRM.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220411203251_SeedDatall")]
    partial class SeedDatall
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.Models.PizzaMenu.PizzaMasterMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PizzaMasterMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 504, DateTimeKind.Utc).AddTicks(6649),
                            CreatedBy = 1,
                            Deleted = false,
                            Name = "Chicken Tikka Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 504, DateTimeKind.Utc).AddTicks(6684),
                            CreatedBy = 1,
                            Deleted = false,
                            Name = "Veg Exotic Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 504, DateTimeKind.Utc).AddTicks(6685),
                            CreatedBy = 1,
                            Deleted = false,
                            Name = "Chilly Chicken Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 504, DateTimeKind.Utc).AddTicks(6686),
                            CreatedBy = 1,
                            Deleted = false,
                            Name = "Chilly Paneer Pizza",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaCrust", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrustType")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaCrust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 502, DateTimeKind.Utc).AddTicks(5135),
                            CreatedBy = 1,
                            CrustType = 0,
                            Deleted = false,
                            PizzaId = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 502, DateTimeKind.Utc).AddTicks(5539),
                            CreatedBy = 1,
                            CrustType = 1,
                            Deleted = false,
                            PizzaId = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 502, DateTimeKind.Utc).AddTicks(5563),
                            CreatedBy = 1,
                            CrustType = 3,
                            Deleted = false,
                            PizzaId = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 502, DateTimeKind.Utc).AddTicks(5565),
                            CreatedBy = 1,
                            CrustType = 2,
                            Deleted = false,
                            PizzaId = 4,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("SizeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaSize");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5317),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5504),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5513),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5514),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5515),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5516),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5517),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5519),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5520),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5521),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 506, DateTimeKind.Utc).AddTicks(5522),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 0,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaToppings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaToppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2327),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 5,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2524),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2534),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2536),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2537),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2538),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2539),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2540),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2543),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2544),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 6,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2545),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 11, 20, 32, 51, 508, DateTimeKind.Utc).AddTicks(2546),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 1,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.User.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaCrust", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaCrust")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaCrust_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaSize", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaSize")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaSize_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaToppings", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaToppings")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaToppings_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
