// <auto-generated />
using System;
using CRM.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220412231710_PizzaPriceModifyAddV11")]
    partial class PizzaPriceModifyAddV11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.Models.PizzaMenu.PizzaMasterMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PizzaMasterMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 542, DateTimeKind.Utc).AddTicks(2069),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "Classic delight with 100% real mozzarella cheese",
                            ImageUrl = "https://images.dominos.co.in/farmhouse.png",
                            Name = "Chicken Tikka Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 542, DateTimeKind.Utc).AddTicks(2340),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "Delightful combination of onion, capsicum, tomato & grilled mushroom",
                            ImageUrl = "https://images.dominos.co.in/new_veggie_paradise.jpg",
                            Name = "Veg Exotic Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 542, DateTimeKind.Utc).AddTicks(2362),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "American classic! Spicy, herbed chicken sausage on pizza",
                            ImageUrl = "https://images.dominos.co.in/new_pepper_barbeque_chicken.jpg",
                            Name = "Chilly Chicken Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 542, DateTimeKind.Utc).AddTicks(2363),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "Pepper barbecue chicken for that extra zing",
                            ImageUrl = "https://images.dominos.co.in/new_peppy_paneer.jpg",
                            Name = "Chilly Paneer Pizza",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.CrustPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrustType")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PizzaCrustId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaCrustId");

                    b.ToTable("CrustPrice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 538, DateTimeKind.Utc).AddTicks(8901),
                            CreatedBy = 1,
                            CrustType = 0,
                            Deleted = false,
                            Price = 10,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 538, DateTimeKind.Utc).AddTicks(9267),
                            CreatedBy = 1,
                            CrustType = 1,
                            Deleted = false,
                            Price = 5,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 538, DateTimeKind.Utc).AddTicks(9283),
                            CreatedBy = 1,
                            CrustType = 3,
                            Deleted = false,
                            Price = 7,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 538, DateTimeKind.Utc).AddTicks(9285),
                            CreatedBy = 1,
                            CrustType = 2,
                            Deleted = false,
                            Price = 12,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaCrust", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrustType")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int?>("PizzaMasterMenuId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaMasterMenuId");

                    b.ToTable("PizzaCrust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 540, DateTimeKind.Utc).AddTicks(8621),
                            CreatedBy = 1,
                            CrustType = 0,
                            Deleted = false,
                            PizzaId = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 540, DateTimeKind.Utc).AddTicks(8783),
                            CreatedBy = 1,
                            CrustType = 1,
                            Deleted = false,
                            PizzaId = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 540, DateTimeKind.Utc).AddTicks(8790),
                            CreatedBy = 1,
                            CrustType = 3,
                            Deleted = false,
                            PizzaId = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 540, DateTimeKind.Utc).AddTicks(8792),
                            CreatedBy = 1,
                            CrustType = 2,
                            Deleted = false,
                            PizzaId = 4,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaPrice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 551, DateTimeKind.Utc).AddTicks(4752),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            Price = 10,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 551, DateTimeKind.Utc).AddTicks(4912),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            Price = 12,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 551, DateTimeKind.Utc).AddTicks(4918),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            Price = 15,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 551, DateTimeKind.Utc).AddTicks(4920),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            Price = 17,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("SizeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaSize");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1529),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1711),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1719),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1721),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1722),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1723),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1724),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1725),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1726),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1727),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 553, DateTimeKind.Utc).AddTicks(1728),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 0,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaToppings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaToppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(6867),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 5,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7018),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7024),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7026),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7027),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7028),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7029),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7030),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7032),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7033),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 6,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7034),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 554, DateTimeKind.Utc).AddTicks(7035),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 1,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.ToppingsPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("ToppingType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToppingsPrice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6221),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 10,
                            ToppingType = 4,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6374),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 5,
                            ToppingType = 5,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6383),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 4,
                            ToppingType = 6,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6384),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 2,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6385),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 4,
                            ToppingType = 4,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6386),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 3,
                            ToppingType = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6387),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 1,
                            ToppingType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 23, 17, 10, 556, DateTimeKind.Utc).AddTicks(6388),
                            CreatedBy = 1,
                            Deleted = false,
                            Price = 2,
                            ToppingType = 0,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.User.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CRM.Models.RelationModel.CrustPrice", b =>
                {
                    b.HasOne("CRM.Models.RelationModel.PizzaCrust", "PizzaCrust")
                        .WithMany("CrustPrice")
                        .HasForeignKey("PizzaCrustId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaCrust", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaCrust")
                        .HasForeignKey("PizzaMasterMenuId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaPrice", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaPrice")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaPrice_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaSize", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaSize")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaSize_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaToppings", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaToppings")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaToppings_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
