// <auto-generated />
using System;
using CRM.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220412134519_PizzaMasterDesc")]
    partial class PizzaMasterDesc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.Models.PizzaMenu.PizzaMasterMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PizzaMasterMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 810, DateTimeKind.Utc).AddTicks(4015),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "Classic delight with 100% real mozzarella cheese",
                            ImageUrl = "https://images.dominos.co.in/farmhouse.png",
                            Name = "Chicken Tikka Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 810, DateTimeKind.Utc).AddTicks(4320),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "Delightful combination of onion, capsicum, tomato & grilled mushroom",
                            ImageUrl = "https://images.dominos.co.in/new_veggie_paradise.jpg",
                            Name = "Veg Exotic Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 810, DateTimeKind.Utc).AddTicks(4333),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "American classic! Spicy, herbed chicken sausage on pizza",
                            ImageUrl = "https://images.dominos.co.in/new_pepper_barbeque_chicken.jpg",
                            Name = "Chilly Chicken Pizza",
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 810, DateTimeKind.Utc).AddTicks(4334),
                            CreatedBy = 1,
                            Deleted = false,
                            Description = "Pepper barbecue chicken for that extra zing",
                            ImageUrl = "https://images.dominos.co.in/new_peppy_paneer.jpg",
                            Name = "Chilly Paneer Pizza",
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaCrust", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CrustType")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaCrust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 808, DateTimeKind.Utc).AddTicks(575),
                            CreatedBy = 1,
                            CrustType = 0,
                            Deleted = false,
                            PizzaId = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 808, DateTimeKind.Utc).AddTicks(972),
                            CreatedBy = 1,
                            CrustType = 1,
                            Deleted = false,
                            PizzaId = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 808, DateTimeKind.Utc).AddTicks(991),
                            CreatedBy = 1,
                            CrustType = 3,
                            Deleted = false,
                            PizzaId = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 808, DateTimeKind.Utc).AddTicks(992),
                            CreatedBy = 1,
                            CrustType = 2,
                            Deleted = false,
                            PizzaId = 4,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("SizeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaSize");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5146),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5323),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5346),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5347),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5349),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            SizeType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5350),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5351),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5352),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            SizeType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5353),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5354),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 812, DateTimeKind.Utc).AddTicks(5356),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            SizeType = 0,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaToppings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PizzaId");

                    b.ToTable("PizzaToppings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1745),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 5,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1920),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1927),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 1,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1929),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1930),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 1,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1931),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 2,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1932),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 3,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1933),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1934),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 3,
                            ToppingType = 0,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1936),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 6,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1937),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 2,
                            UpdatedBy = 0
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2022, 4, 12, 13, 45, 18, 814, DateTimeKind.Utc).AddTicks(1938),
                            CreatedBy = 1,
                            Deleted = false,
                            PizzaId = 4,
                            ToppingType = 1,
                            UpdatedBy = 0
                        });
                });

            modelBuilder.Entity("CRM.Models.User.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int")
                        .HasMaxLength(25);

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaCrust", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaCrust")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaCrust_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaSize", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaSize")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaSize_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM.Models.RelationModel.PizzaToppings", b =>
                {
                    b.HasOne("CRM.Models.PizzaMenu.PizzaMasterMenu", "PizzaMasterMenu")
                        .WithMany("PizzaToppings")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK_PizzaToppings_Master")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
